#!/bin/bash
# Update Arco Linux

# Make sure each command executes properly
check_exit_status() {

	if [ $? -eq 0 ]
	then
		echo
		echo "Success"
		echo
	else
		echo
		echo "[ERROR] Process Failed!"
		echo
		
		read -p "The last command exited with an error. Exit script? (yes/no) " answer

            if [ "$answer" == "y" ]
            then
                exit 1
            fi
	fi
}

greeting() {

    echo
    echo "Hello, $USER. Let's update your ArcoLinux."
    echo
}

# search for the fastest mirrors
function mirror() {

	echo "Updating your Mirrors."
	sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist;
	check_exit_status
}

# Download and install all Arch Linux and ArcoLinux packages
function general_update() {

	echo "Updating Arch & Arco."
    sudo pacman -Syyu --noconfirm;
    check_exit_status
}

# Copy/paste all config files from /etc/skel to your home directory
function skel() {

	echo "Running Skel."
    cp -rf /etc/skel/. ~;
    check_exit_status
}

# Put the fancy bash promt back after updating
function fix_bashrc() {

	echo "Putting Bashrc back together."
    echo "source ~/.fancy-bash-promt.sh" >> ~/.bashrc-latest
    check_exit_status
}

# Copy over all new bashrc changes, including fix_bashrc
function copy_over_newest_bashrc() {

    cp ~/.bashrc-latest ~/.bashrc && source ~/.bashrc && sudo cp /etc/skel/.bashrc-latest /etc/skel/.bashrc;
    check_exit_status
}

# Now update the rest – Only AUR packages will now be updated
function aur_update() {

	echo "Updating the AUR."
    yay -Syu --noconfirm;
    check_exit_status
}

# Perform the maintenance and clean-up duties, remove orphaned files to keep the system running optimally
function housekeeping() {

	echo "Cleaning up."
    sudo pacman -Rns $(pacman -Qtdq) --noconfirm;
#    check_exit_status
}

function leave() {

    echo
    echo "-------------------------------"
    echo "- ArcoLinux has been updated! -"
    echo "-------------------------------"
    echo

# Stay Rolling
function Stay_Rolling() {

	echo "Now Stay Rolling.";
	cd $HOME/.bin/stay-rolling;
	ls
	exit
}

greeting
mirror
general_update
skel
fix_bashrc
copy_over_newest_bashrc
aur_update
housekeeping
leave
Stay_Rolling
